version: '3'
services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
