frontend:
  replicaCount: 3
  image:
    repository: gcr.io/molten-enigma-425106-p0/tutorial-1
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 100Mi

redis:
  master:
    replicaCount: 1
    image:
      repository: redis
      tag: 6.2.6
  slave:
    replicaCount: 2
    image:
      repository: gcr.io/google_samples/gb-redisslave
      tag: v3
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
