frontend:
  replicaCount: 3
  image:
    repository: gcr.io/molten-enigma-425106-p0/tutorial-1
    tag: v4
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
  env:
    REDIS_HOST: redis-master
    REDIS_PORT: "6379"

redis:
  master:
    replicaCount: 1
    image:
      repository: k8s.gcr.io/redis
      tag: e2e
  slave:
    replicaCount: 2
    image:
      repository: gcr.io/google_samples/gb-redisslave
      tag: v3
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
